"""I testi delle schermate di Spending Review (F12.4), letti da tool/testi.py.

Un file per parte dell'app (vedi tutti_i_testi() in testi.py). Virgolette tipografiche (“…”, ’)
anche in inglese; nessun glifo di spunta o di avviso (guardia texts_glyphs_test.dart): le icone
sono icone. Gli importi arrivano gia' scritti con la virgola (lib/app/labels.dart), anche in
inglese: l'app e' in euro e il tastierino «alla cassa» mostra la virgola.
"""

TIPI = {
    'spese': 'int', 'negozi': 'int', 'prendi': 'int', 'percento': 'int', 'euro': 'int', 'cent': 'int',
}

TESTI = {
    # ── Comuni ──
    'common_add': ('Add', 'Aggiungi'),
    'common_ok': ('OK', 'OK'),
    'common_close': ('Close', 'Chiudi'),

    # ── La spesa (F12.1.12) ──
    'spesa_vuota': ('Key in a price or scan a price tag', 'Batti un prezzo o inquadra un cartellino'),
    'spesa_prezzoAMano': ('Price by hand', 'Prezzo a mano'),
    'spesa_cartellino': ('Price tag', 'Cartellino'),
    'spesa_scontrino': ('Receipt', 'Scontrino'),
    'spesa_statoConBudget': ('{n, plural, =1{1 item} other{{n} items}} · budget {budget} €',
                             '{n, plural, =1{1 articolo} other{{n} articoli}} · budget {budget} €'),
    'spesa_statoSenzaBudget': ('{n, plural, =1{1 item} other{{n} items}} · set a budget',
                               '{n, plural, =1{1 articolo} other{{n} articoli}} · imposta un budget'),
    'spesa_eliminato': ('Removed', 'Eliminato'),
    'spesa_iniziataIeri': ('Shopping started yesterday at {ora}', 'Spesa iniziata ieri alle {ora}'),
    'spesa_iniziataIl': ('Shopping started on {giorno} at {ora}', 'Spesa iniziata il {giorno} alle {ora}'),
    'spesa_chiudila': ('Close it', 'Chiudila'),
    'spesa_continua': ('Continue', 'Continua'),
    'semantica_euro': ('{euro} euros and {cent}', '{euro} euro e {cent}'),
    'semantica_totale': ('Total {totale}', 'Totale {totale}'),
    'semantica_totaleResiduo': ('Total {totale}, {residuo} left in the budget', 'Totale {totale}, mancano {residuo} al budget'),
    'semantica_totaleSforato': ('Total {totale}, {sforo} over the budget', 'Totale {totale}, {sforo} oltre il budget'),

    # ── Tastierino ──
    'tasto_cancella': ('delete', 'cancella'),
    'tasto_per': ('times', 'per'),
    'tasto_meno': ('minus', 'meno'),
    'tasto_aggiungi': ('add', 'aggiungi'),
    'tasto_virgola': ('comma', 'virgola'),
    'tasto_doppioZero': ('double zero', 'doppio zero'),
    'tasto_svuota': ('clear', 'svuota'),

    # ── Budget ──
    'budget_titoloSpesa': ('Budget for this shopping trip', 'Budget di questa spesa'),
    'budget_importo': ('Amount', 'Importo'),
    'budget_usaAbituale': ('Use it for the next shopping trips too', 'Usalo anche per le prossime spese'),
    'budget_nessuno': ('No budget', 'Nessun budget'),

    # ── Una riga ──
    'riga_titolo': ('Item', 'Articolo'),
    'riga_nome': ('Name', 'Nome'),
    'riga_prezzo': ('Price', 'Prezzo'),
    'riga_prezzoAl': ('Price per {unita}', 'Prezzo al {unita}'),
    'riga_importo': ('Amount', 'Importo'),
    'riga_totaleStampato': ('Total on the label', 'Totale dell’etichetta'),
    'riga_quantita': ('Quantity', 'Quantità'),
    'riga_menoUno': ('One less', 'Uno in meno'),
    'riga_piuUno': ('One more', 'Uno in più'),
    'riga_peso': ('Weight', 'Peso'),
    'riga_ePrezzoAlKg': ('It’s a price per kg', 'È un prezzo al kg'),
    'riga_offerta': ('Offer', 'Offerta'),
    'riga_offertaNessuna': ('None', 'Nessuna'),
    'riga_totale': ('Line total: {importo} €', 'Totale della riga: {importo} €'),

    # ── Offerte ──
    'offerta_anziche': ('instead of {prezzo}', 'anziché {prezzo}'),
    'offerta_conCarta': ('with card (without: {prezzo})', 'con carta (senza: {prezzo})'),
    'offerta_nxmLunga': ('{offerta} · {effettivo} each if you take {prendi}', '{offerta} · {effettivo} cad. se ne prendi {prendi}'),
    'offerta_percentoLunga': ('−{percento}% at the till · {scontato}', '−{percento}% alla cassa · {scontato}'),
    'offerta_secondoLunga': ('−{percento}% on the second one', '−{percento}% sul secondo pezzo'),
    'offerta_barratoLunga': ('Instead of {pieno} · you save {risparmio}', 'Anziché {pieno} · risparmi {risparmio}'),
    'offerta_cartaLunga': ('With card · without card {senza}', 'Con carta · senza carta {senza}'),

    # ── Fotocamera (comune a cartellino e scontrino) ──
    'fotocamera_scatta': ('Take photo', 'Scatta'),
    'fotocamera_daFoto': ('From a photo', 'Da una foto'),
    'fotocamera_torcia': ('Torch', 'Torcia'),
    'fotocamera_negataTitolo': ('The camera is off', 'La fotocamera è spenta'),
    'fotocamera_negataTesto': ('Spending Review needs the camera to read price tags and receipts. You can still use the keypad, or pick a photo.',
                               'Spending Review usa la fotocamera per leggere cartellini e scontrini. Il tastierino funziona lo stesso, e puoi scegliere una foto.'),
    'fotocamera_erroreTitolo': ('The camera didn’t start', 'La fotocamera non è partita'),
    'fotocamera_erroreTesto': ('Try again, or pick a photo you already took.', 'Riprova, oppure scegli una foto che hai già scattato.'),
    'fotocamera_apriImpostazioni': ('Open settings', 'Apri le impostazioni'),

    # ── Cartellino ──
    'cartellino_titolo': ('Price tag', 'Cartellino'),
    'cartellino_modoCartellino': ('Price tag', 'Cartellino'),
    'cartellino_modoBilancia': ('Scale', 'Bilancia'),
    'cartellino_inquadra': ('Frame one price tag, up close', 'Inquadra un cartellino, da vicino'),
    'cartellino_scrittoAMano': ('I can’t read handwriting: for that there’s the keypad', 'Lo scritto a mano non lo leggo: per quello c’è il tastierino'),
    'cartellino_leggo': ('Reading…', 'Leggo…'),
    'cartellino_scattoFallito': ('The photo didn’t work. Try again.', 'La foto non è riuscita. Riprova.'),
    'cartellino_ocrAssente': ('This phone can’t read price tags: use the keypad', 'Su questo telefono non riesco a leggere i cartellini: usa il tastierino'),
    'cartellino_nienteLetto': ('I couldn’t find a price. Get closer, or use the keypad.', 'Non ho trovato un prezzo. Avvicinati, o usa il tastierino.'),
    'cartellino_forseAMano': ('I read some text but no price: if it’s handwritten, use the keypad.', 'Ho letto del testo ma nessun prezzo: se è scritto a mano, usa il tastierino.'),
    'cartellino_conferma': ('Price tag read', 'Cartellino letto'),
    'cartellino_prezzoSemantica': ('Price {prezzo} euros, tap to change it', 'Prezzo {prezzo} euro, tocca per cambiarlo'),
    'cartellino_controlla': ('Check the price', 'Controlla il prezzo'),
    'cartellino_cartaDomanda': ('This price tag has two prices: which one do you pay?', 'Questo cartellino ha due prezzi: quale paghi?'),
    'cartellino_conCarta': ('With the loyalty card: {prezzo}', 'Con la carta fedeltà: {prezzo}'),
    'cartellino_senzaCarta': ('Without the card: {prezzo}', 'Senza la carta: {prezzo}'),
    'cartellino_aggiungiOra': ('Add (now {n})', 'Aggiungi (ora {n})'),
    'cartellino_battiAMano': ('Key it in', 'Batti a mano'),
    'cartellino_quale': ('{n, plural, =1{I saw 1 price tag} other{I saw {n} price tags: which one?}}',
                         '{n, plural, =1{Ho visto 1 cartellino} other{Ho visto {n} cartellini: quale?}}'),

    # ── Peso ──
    'peso_titolo': ('Weight', 'Peso'),
    'peso_etichetta': ('Weight', 'Peso'),
    'peso_suggerimento': ('Key in the weight in grams, or in kg with the comma', 'Batti il peso in grammi, o in kg con la virgola'),
    'peso_cambiaUnita': ('switch to {unita}', 'passa a {unita}'),
    'peso_aggiungiPrezzo': ('Add · {importo} €', 'Aggiungi · {importo} €'),
    'peso_leggiBilancia': ('Read the scale label', 'Leggi l’etichetta della bilancia'),

    # ── Bilancia ──
    'bilancia_titolo': ('Scale label', 'Etichetta della bilancia'),
    'bilancia_inquadra': ('Frame the scale label, up close', 'Inquadra l’etichetta della bilancia, da vicino'),
    'bilancia_nonTorna': ('Weight × price doesn’t add up: check', 'Il conto peso × prezzo non torna: controlla'),
    'bilancia_peso': ('Net weight', 'Peso netto'),
    'bilancia_alKg': ('Price per kg', 'Prezzo al kg'),
    'bilancia_totaleEtichetta': ('Total on the label', 'Totale dell’etichetta'),

    # ── Scontrino ──
    'scontrino_titolo': ('Receipt', 'Scontrino'),
    'scontrino_titoloParti': ('{n, plural, =1{Receipt · 1 photo} other{Receipt · {n} photos}}',
                              '{n, plural, =1{Scontrino · 1 foto} other{Scontrino · {n} foto}}'),
    'scontrino_inquadra': ('Frame the receipt straight, full width', 'Inquadra lo scontrino dritto, tutto in larghezza'),
    'scontrino_inquadraPezzo': ('Part {n}: frame the next piece, overlapping a couple of lines', 'Pezzo {n}: inquadra il seguito, con un paio di righe in comune'),
    'scontrino_leggi': ('Read', 'Leggi'),
    'scontrino_aggiungiPezzo': ('Add a piece', 'Aggiungi un pezzo'),
    'scontrino_massimoPezzi': ('At most {n} pieces', 'Al massimo {n} pezzi'),
    'scontrino_togliPezzo': ('Remove piece {n}', 'Togli il pezzo {n}'),
    'scontrino_nienteLetto': ('I couldn’t read the receipt. Try again, closer and straight.', 'Non sono riuscito a leggere lo scontrino. Riprova, più vicino e dritto.'),
    'scontrino_ocrAssente': ('This phone can’t read receipts.', 'Su questo telefono non riesco a leggere gli scontrini.'),

    # ── Confronto ──
    'confronto_titolo': ('Receipt vs your count', 'Scontrino contro conto'),
    'confronto_scontrino': ('Receipt', 'Scontrino'),
    'confronto_contato': ('Counted', 'Contato'),
    'confronto_tuttoTorna': ('It all adds up', 'Tutto torna'),
    'confronto_daGuardare': ('A difference to look at', 'Differenza da guardare'),
    'confronto_sospette': ('Lines to check', 'Righe da guardare'),
    'confronto_notaPrezzo': ('price tag {cartellino} · receipt {scontrino}', 'cartellino {cartellino} · scontrino {scontrino}'),
    'confronto_notaSoloScontrino': ('only on the receipt', 'solo sullo scontrino'),
    'confronto_notaNonScontrino': ('counted but not on the receipt', 'contato ma non sullo scontrino'),
    'confronto_notaDoppia': ('on the receipt twice?', 'sullo scontrino due volte?'),
    'confronto_tornano': ('{n, plural, =1{Lines that match (1)} other{Lines that match ({n})}}',
                          '{n, plural, =1{Righe che tornano (1)} other{Righe che tornano ({n})}}'),
    'confronto_nonQuadra': ('{n, plural, =0{The total read doesn’t match the sum of the lines} =1{The total read doesn’t match the sum of the lines: 1 line not read} other{The total read doesn’t match the sum of the lines: {n} lines not read}}',
                            '{n, plural, =0{Il totale letto non corrisponde alla somma delle righe} =1{Il totale letto non corrisponde alla somma delle righe: 1 riga non letta} other{Il totale letto non corrisponde alla somma delle righe: {n} righe non lette}}'),
    'confronto_giunzione': ('I joined {n} photos without finding where they overlap: some lines may be doubled or missing',
                            'Ho unito {n} foto senza trovare il punto di unione: qualche riga potrebbe essere doppia o mancare'),
    'confronto_rifotografa': ('Photograph the receipt again', 'Rifotografa lo scontrino'),
    'confronto_rigaContata': ('Counted: {testo}', 'Contato: {testo}'),
    'confronto_rigaScontrino': ('Receipt: {testo}', 'Scontrino: {testo}'),

    # ── Registrazione dallo scontrino ──
    'registra_titolo': ('Save from the receipt', 'Registra dallo scontrino'),
    'registra_salva': ('Save the shopping trip', 'Salva la spesa'),
    'registra_totaleStampato': ('Total on the receipt', 'Totale dello scontrino'),
    'registra_sommaRighe': ('Sum of the lines', 'Somma delle righe'),
    'registra_senzaTotale': ('I didn’t find the TOTAL: I’ll save the sum of the lines', 'Non ho trovato il TOTALE: salvo la somma delle righe'),
    'registra_nonQuadra': ('{n, plural, =0{The lines add up to {somma}: check them} =1{The lines add up to {somma}: 1 line not read} other{The lines add up to {somma}: {n} lines not read}}',
                           '{n, plural, =0{Le righe fanno {somma}: controllale} =1{Le righe fanno {somma}: 1 riga non letta} other{Le righe fanno {somma}: {n} righe non lette}}'),
    'registra_righe': ('{n, plural, =1{1 line} other{{n} lines}}', '{n, plural, =1{1 riga} other{{n} righe}}'),
    'registra_stornata': ('cancelled at the till', 'stornata alla cassa'),

    # ── Chiusura ──
    'chiusura_titolo': ('Close the shopping trip', 'Chiudi la spesa'),
    'chiusura_niente': ('There’s nothing to save.', 'Non c’è niente da salvare.'),
    'chiusura_buttaVia': ('Throw it away', 'Butta via'),
    'chiusura_buttaViaTitolo': ('Throw away this shopping trip?', 'Buttare via questa spesa?'),
    'chiusura_buttaViaTesto': ('All its lines are deleted. It can’t be undone.', 'Tutte le sue righe vengono cancellate. Non si può annullare.'),
    'chiusura_dentro': ('Within budget by {importo}', 'Dentro il budget di {importo}'),
    'chiusura_sforato': ('Over budget by {importo}', 'Sforato di {importo}'),
    'chiusura_quali': ('Which lines to keep', 'Quali righe salvare'),
    'chiusura_righeScontrino': ('The receipt’s lines', 'Le righe dello scontrino'),
    'chiusura_righeContate': ('The lines you counted', 'Le righe contate'),
    'chiusura_negozio': ('Shop', 'Negozio'),
    'chiusura_data': ('Date', 'Data'),
    'chiusura_salvata': ('Saved.', 'Salvata.'),
    'chiusura_salvataGratis': ('Saved. On the free plan you see the last 5: the others stay on your phone.',
                               'Salvata. Nel piano gratuito vedi le ultime 5: le altre restano sul telefono.'),

    # ── Negozi ──
    'negozio_altro': ('Other…', 'Altro…'),
    'negozio_titolo': ('Shop', 'Negozio'),
    'negozio_nome': ('Shop name', 'Nome del negozio'),
    'negozi_titolo': ('Shops', 'Negozi'),
    'negozi_rinomina': ('Rename the shop', 'Rinomina il negozio'),
    'negozi_doppione': ('There’s already a shop with that name.', 'C’è già un negozio con questo nome.'),
    'negozi_eliminaTitolo': ('Delete “{nome}”?', 'Eliminare “{nome}”?'),
    'negozi_eliminaTesto': ('Its shopping trips stay, without a shop.', 'Le sue spese restano, senza negozio.'),
    'negozi_vuotoTitolo': ('No shops yet', 'Ancora nessun negozio'),
    'negozi_vuotoTesto': ('A shop is added when you choose it while closing a shopping trip.', 'Un negozio si aggiunge quando lo scegli chiudendo una spesa.'),

    # ── Storico ──
    'storico_vuotoTitolo': ('No shopping trips yet', 'Ancora nessuna spesa'),
    'storico_vuotoTesto': ('When you close a shopping trip, it ends up here.', 'Quando chiudi una spesa, finisce qui.'),
    'storico_mese': ('{mese} · {n, plural, =1{1 trip} other{{n} trips}} · {totale} €', '{mese} · {n, plural, =1{1 spesa} other{{n} spese}} · {totale} €'),
    'storico_altre': ('{n, plural, =1{1 more shopping trip is on your phone: with Pro you see them all, with statistics} other{{n} more shopping trips are on your phone: with Pro you see them all, with statistics}}',
                      '{n, plural, =1{Un’altra spesa è sul telefono: con il Pro le rivedi tutte, con le statistiche} other{Le altre {n} spese sono sul telefono: con il Pro le rivedi tutte, con le statistiche}}'),
    'storico_sforata': ('over budget', 'budget sforato'),
    'storico_vicina': ('close to the budget', 'vicina al budget'),

    # ── Dettaglio ──
    'dettaglio_titolo': ('Shopping trip', 'Spesa'),
    'dettaglio_nascosta': ('This shopping trip is on your phone, but the free plan shows only the last 5. With Pro you see them all.',
                           'Questa spesa è sul telefono, ma il piano gratuito mostra solo le ultime 5. Con il Pro le rivedi tutte.'),
    'dettaglio_budgetDentro': ('Budget {budget} · {residuo} left', 'Budget {budget} · avanzano {residuo}'),
    'dettaglio_budgetSforato': ('Budget {budget} · over by {sforo}', 'Budget {budget} · sforato di {sforo}'),
    'dettaglio_righeContate': ('Counted lines', 'Righe contate'),
    'dettaglio_righeScontrino': ('Receipt lines', 'Righe dello scontrino'),
    'dettaglio_mostraContate': ('Also show the counted lines', 'Mostra anche le righe contate'),
    'dettaglio_mostraScontrino': ('Also show the receipt lines', 'Mostra anche le righe dello scontrino'),
    'dettaglio_nascondiAltre': ('Hide the other lines', 'Nascondi le altre righe'),
    'dettaglio_eliminaTitolo': ('Delete this shopping trip?', 'Eliminare questa spesa?'),
    'dettaglio_eliminaTesto': ('It disappears from history and statistics. It can’t be undone.', 'Sparisce dallo storico e dalle statistiche. Non si può annullare.'),

    # ── Statistiche ──
    'statistiche_mesePrima': ('Previous month', 'Mese prima'),
    'statistiche_meseDopo': ('Next month', 'Mese dopo'),
    'statistiche_totaleMese': ('Month total', 'Totale del mese'),
    'statistiche_spese': ('Trips', 'Spese'),
    'statistiche_media': ('Average', 'Spesa media'),
    'statistiche_sforamenti': ('Over budget', 'Sforamenti'),
    'statistiche_sforamentiSu': ('out of {n} with a budget', 'su {n} con budget'),
    'statistiche_ultimiSei': ('Last 6 months', 'Ultimi 6 mesi'),
    'statistiche_perNegozio': ('By shop', 'Per negozio'),
    'statistiche_questoMese': ('This month', 'Il mese'),
    'statistiche_dodiciMesi': ('Last 12 months', 'Ultimi 12 mesi'),
    'statistiche_negozio': ('Shop', 'Negozio'),
    'statistiche_totale': ('Total', 'Totale'),
    'statistiche_nessunaSpesa': ('No shopping trips in this period.', 'Nessuna spesa in questo periodo.'),
    'statistiche_budgetMese': ('Monthly budget', 'Budget del mese'),
    'statistiche_spesoSu': ('{speso} € of {tetto} €', '{speso} € su {tetto} €'),
    'statistiche_tettoResiduo': ('{importo} € left this month', 'Restano {importo} € questo mese'),
    'statistiche_tettoSforato': ('{importo} € over the monthly budget', '{importo} € oltre il budget del mese'),
    'statistiche_tettoNessuno': ('Set a ceiling for the whole month.', 'Imposta un tetto per tutto il mese.'),
    'statistiche_tettoImposta': ('Set', 'Imposta'),
    'statistiche_tettoCambia': ('Change', 'Cambia'),
    'statistiche_tettoTitolo': ('Monthly budget', 'Budget del mese'),
    'grafico_titolo': ('Monthly totals: {valori}', 'Totali dei mesi: {valori}'),
    'grafico_mese': ('{mese} {importo} euros', '{mese} {importo} euro'),

    # ── Impostazioni ──
    'impostazioni_spesa': ('Shopping', 'La spesa'),
    'impostazioni_budgetAbituale': ('Usual budget', 'Budget abituale'),
    'impostazioni_budgetNessuno': ('None: each trip starts without a budget', 'Nessuno: ogni spesa parte senza budget'),
    'impostazioni_vibrazione': ('Vibration', 'Vibrazione'),
    'impostazioni_vibrazioneTesto': ('A short buzz on every key and when you pass the budget thresholds', 'Una vibrazione breve a ogni tasto e alle soglie del budget'),
    'impostazioni_pro': ('Pro', 'Pro'),
    'impostazioni_informazioni': ('About', 'Informazioni'),
    'impostazioni_privacy': ('Privacy', 'Informativa sulla privacy'),
    'impostazioni_privacyTesto': ('Photos of price tags and receipts are read on your phone (on iPhone by Apple’s own system, on Android by an engine built into the app) and deleted right after reading. No photo and no shopping data leaves your phone. The only outside communication is buying the Pro version (Google Play / App Store) and, on Android, checking it on our server. Your shopping history is kept out of automatic cloud backups: you make a backup yourself, with Pro, in a file you can see.',
                                  'Le foto di cartellini e scontrini vengono lette sul telefono (su iPhone dal sistema di Apple, su Android da un motore incluso nell’app) e cancellate subito dopo la lettura. Nessuna foto e nessun dato della spesa esce dal telefono. L’unica comunicazione esterna è l’acquisto della versione Pro (Google Play / App Store) e, su Android, la sua verifica sul nostro server. Lo storico della spesa resta fuori dai backup automatici nel cloud: il backup lo fai tu, con il Pro, in un file che vedi.'),
    'impostazioni_licenze': ('Licences', 'Licenze'),

    # ── I tuoi dati ──
    'dati_titolo': ('Your data', 'I tuoi dati'),
    'backup_crea': ('Create a backup', 'Crea un backup'),
    'backup_creaTesto': ('All your shopping trips in one file, to keep or move to a new phone', 'Tutte le spese in un file, da tenere o portare su un telefono nuovo'),
    'backup_creaFallito': ('The backup couldn’t be created.', 'Non sono riuscito a creare il backup.'),
    'backup_inCorso': ('Creating the backup…', 'Creo il backup…'),
    'backup_oggetto': ('Spending Review backup', 'Backup di Spending Review'),
    'backup_ripristina': ('Restore a backup', 'Ripristina un backup'),
    'backup_ripristinaTesto': ('Free: bring back your shopping trips from a file', 'Gratis: riporta le spese da un file'),
    'backup_ripristinaTitolo': ('Restore this backup?', 'Ripristinare questo backup?'),
    'backup_riepilogo': ('{spese, plural, =1{1 shopping trip} other{{spese} shopping trips}}, {negozi, plural, =1{1 shop} other{{negozi} shops}}',
                         '{spese, plural, =1{1 spesa} other{{spese} spese}}, {negozi, plural, =1{1 negozio} other{{negozi} negozi}}'),
    'backup_modoSostituisci': ('Replace everything', 'Sostituisci tutto'),
    'backup_modoSostituisciTesto': ('What’s on the phone now is deleted', 'Quello che c’è ora sul telefono viene cancellato'),
    'backup_modoUnisci': ('Merge', 'Unisci'),
    'backup_modoUnisciTesto': ('Keeps what’s on the phone and adds the rest', 'Tiene quello che c’è sul telefono e aggiunge il resto'),
    'backup_ripristinoInCorso': ('Restoring…', 'Ripristino…'),
    'backup_ripristinato': ('Backup restored.', 'Backup ripristinato.'),
    'backup_fallito': ('This file isn’t a Spending Review backup, or it can’t be read.', 'Questo file non è un backup di Spending Review, o non si legge.'),

    # ── CSV ──
    'csv_titolo': ('Export CSV', 'Esporta CSV'),
    'csv_testo': ('Every item of every shopping trip, for a spreadsheet', 'Ogni articolo di ogni spesa, per un foglio di calcolo'),
    'csv_vuoto': ('There are no closed shopping trips to export yet.', 'Non ci sono ancora spese chiuse da esportare.'),
    'csv_fallito': ('The CSV couldn’t be created.', 'Non sono riuscito a creare il CSV.'),
    'csv_data': ('Date', 'Data'),
    'csv_negozio': ('Shop', 'Negozio'),
    'csv_spesa': ('Trip no.', 'Spesa n.'),
    'csv_articolo': ('Item', 'Articolo'),
    'csv_quantita': ('Quantity', 'Quantità'),
    'csv_unita': ('Unit', 'Unità'),
    'csv_prezzoUnitario': ('Unit price', 'Prezzo unitario'),
    'csv_offerta': ('Offer', 'Offerta'),
    'csv_totaleRiga': ('Line total', 'Totale riga'),
    'csv_totaleSpesa': ('Trip total', 'Totale spesa'),
    'csv_budget': ('Budget', 'Budget'),
    'csv_origine': ('Source', 'Origine'),
    'csv_pezzi': ('pcs', 'pz'),
    'origine_tastierino': ('keypad', 'tastierino'),
    'origine_cartellino': ('price tag', 'cartellino'),
    'origine_bilancia': ('scale', 'bilancia'),
    'origine_scontrino': ('receipt', 'scontrino'),

    # ── Sviluppo (solo debug / SR_DEV) ──
    'dev_titolo': ('Developer tools: OCR', 'Strumenti di sviluppo: OCR'),
    'dev_esporta': ('Export fixture', 'Esporta fixture'),
}
