"""Testi della parte Pro sui dati (F6.10, F6.11). Vedi tool/testi.py.

Prefissi: stats_ (la pagina delle statistiche), data_ (la sezione "I tuoi dati" delle
impostazioni), csv_ (le colonne del CSV dei rullini), backup_ (creazione e ripristino del
backup), report_ (il PDF di riepilogo annuale).

⚑ L'anno passa come testo ({year} senza tipo): un int formattato da gen_l10n potrebbe
diventare "2.026" in italiano.
"""

TESTI = {
    # ── Statistiche (F6.10) ──
    'stats_title': ('Statistics', 'Statistiche'),
    'stats_emptyTitle': ('No statistics yet', 'Ancora niente statistiche'),
    'stats_emptyBody': ('Load your first roll: numbers and costs will appear here, year by year.',
                        'Carica il tuo primo rullino: qui compariranno numeri e costi, anno per anno.'),
    'stats_rolls': ('Rolls', 'Rullini'),
    'stats_potentialFrames': ('Potential frames', 'Fotogrammi potenziali'),
    'stats_potentialFramesHint': ('the frames the rolls had', 'quelli che i rullini avevano'),
    'stats_spending': ('Spending', 'Spesa'),
    'stats_film': ('Film', 'Pellicola'),
    'stats_development': ('Developing', 'Sviluppo'),
    'stats_scans': ('Scans', 'Scansioni'),
    'stats_prints': ('Prints', 'Stampe'),
    'stats_total': ('Total', 'Totale'),
    'stats_noCosts': ('No costs recorded for this year.', 'Nessun costo registrato per quest’anno.'),
    'stats_averages': ('Averages', 'Medie'),
    'stats_perRoll': ('Average cost per roll', 'Costo medio per rullino'),
    'stats_perRollHint': ('{n, plural, =1{on the only roll with costs} other{on the {n} rolls with costs}}',
                          '{n, plural, =1{sull’unico rullino con costi} other{sui {n} rullini con costi}}'),
    'stats_perFrame': ('Cost per frame (estimate)', 'Costo per fotogramma (stima)'),
    'stats_perFrameValue': ('≈ {amount}', '≈ {amount}'),
    'stats_perFrameHint': ('An estimate on the nominal frames: not every frame gets shot, and not every one comes out.',
                           'Una stima sui fotogrammi nominali: non tutti vengono scattati, e non tutti riescono.'),
    'stats_mostUsed': ('Most used', 'I più usati'),
    'stats_topLab': ('Lab', 'Laboratorio'),
    'stats_topEmulsion': ('Film', 'Emulsione'),
    'stats_topCamera': ('Camera', 'Macchina'),
    'stats_noneYet': ('None yet', 'Nessuno, per ora'),
    'stats_rollsCount': ('{n, plural, =1{1 roll} other{{n} rolls}}', '{n, plural, =1{1 rullino} other{{n} rullini}}'),
    'stats_timesCount': ('{n, plural, =1{once} other{{n} times}}', '{n, plural, =1{1 volta} other{{n} volte}}'),
    'stats_selfDeveloped': ('{n, plural, =1{1 roll developed at home} other{{n} rolls developed at home}}',
                            '{n, plural, =1{1 rullino sviluppato in casa} other{{n} rullini sviluppati in casa}}'),
    'stats_perMonth': ('Rolls per month', 'Rullini per mese'),

    # ── Sezione "I tuoi dati" delle impostazioni ──
    'data_title': ('Your data', 'I tuoi dati'),
    'data_statsBody': ('Rolls, spending and favourites, year by year.', 'Rullini, spesa e preferiti, anno per anno.'),

    # ── PDF di riepilogo annuale (F6.11) ──
    'report_title': ('Your year as a PDF', 'Il tuo anno in PDF'),
    'report_body': ('A summary to print: the totals, then a page for each roll with dates, costs and photos.',
                    'Un riepilogo da stampare: i totali, poi una pagina per rullino con date, costi e foto.'),
    'report_chooseYear': ('Which year?', 'Quale anno?'),
    'report_noRolls': ('No rolls yet: the summary needs at least one.', 'Ancora nessun rullino: per il riepilogo ne serve almeno uno.'),
    'report_building': ('Preparing the PDF…', 'Preparo il PDF…'),
    'report_failed': ('The PDF could not be created. Try again.', 'Non sono riuscito a creare il PDF. Riprova.'),
    'report_ready': ('The {year} PDF is ready', 'Il PDF del {year} è pronto'),
    'report_print': ('Print or save', 'Stampa o salva'),
    'report_printBody': ('Opens the print preview of your phone.', 'Apre l’anteprima di stampa del telefono.'),
    'report_share': ('Share', 'Condividi'),
    'report_shareBody': ('Send the file by email, by chat or to your cloud.', 'Manda il file per email, in chat o nel tuo cloud.'),
    'report_subject': ('Film Tracker - {year}', 'Film Tracker - {year}'),
    'report_coverTitle': ('My year on film', 'Il mio anno in pellicola'),
    'report_generated': ('Made with Film Tracker on {date}', 'Creato con Film Tracker il {date}'),
    'report_rollsIndex': ('The rolls', 'I rullini'),
    'report_costs': ('Costs', 'Costi'),
    'report_photos': ('Photos', 'Foto'),
    'report_noPhotos': ('No photos for this roll.', 'Nessuna foto per questo rullino.'),
    'report_noCosts': ('No costs recorded.', 'Nessun costo registrato.'),

    # ── CSV dei rullini (F6.11) ──
    'csv_export': ('Export to a spreadsheet', 'Esporta in un foglio di calcolo'),
    'csv_exportBody': ('Every roll with its dates and costs, as a CSV file that opens in Excel.',
                       'Ogni rullino con le sue date e i suoi costi, in un file CSV che si apre con Excel.'),
    'csv_subject': ('Film Tracker - rolls', 'Film Tracker - rullini'),
    'csv_number': ('Number', 'Numero'),
    'csv_title': ('Title', 'Titolo'),
    'csv_film': ('Film', 'Pellicola'),
    'csv_format': ('Format', 'Formato'),
    'csv_nominalIso': ('Nominal ISO', 'ISO nominale'),
    'csv_exposedIso': ('Exposed ISO', 'ISO di esposizione'),
    'csv_camera': ('Camera', 'Macchina'),
    'csv_status': ('Status', 'Stato'),
    'csv_loadedAt': ('Loaded', 'Caricato'),
    'csv_finishedAt': ('Finished', 'Terminato'),
    'csv_frames': ('Frames', 'Fotogrammi'),
    'csv_filmCost': ('Film cost (€)', 'Costo pellicola (€)'),
    'csv_lab': ('Developing lab', 'Laboratorio sviluppo'),
    'csv_devSubmitted': ('Delivered to the lab', 'Consegnato al laboratorio'),
    'csv_devReturned': ('Back from the lab', 'Ritirato dal laboratorio'),
    'csv_process': ('Process', 'Processo'),
    'csv_selfDeveloped': ('Developed at home', 'Sviluppato in casa'),
    'csv_devCost': ('Developing cost (€)', 'Costo sviluppo (€)'),
    'csv_scanCost': ('Scan cost (€)', 'Costo scansioni (€)'),
    'csv_printOrders': ('Print orders', 'Ordini di stampa'),
    'csv_printCount': ('Prints', 'Copie stampate'),
    'csv_printLabs': ('Print labs', 'Laboratori stampa'),
    'csv_printCost': ('Prints cost (€)', 'Costo stampe (€)'),
    'csv_totalCost': ('Total cost (€)', 'Costo totale (€)'),
    'csv_note': ('Note', 'Nota'),
    'csv_yes': ('Yes', 'Sì'),
    'csv_no': ('No', 'No'),

    # ── Backup (F6.11) ──
    'backup_create': ('Back up everything', 'Fai un backup di tutto'),
    'backup_createBody': ('Rolls, cameras, developing, prints and photos in one file, to keep or move to a new phone.',
                          'Rullini, macchine, sviluppi, stampe e foto in un solo file, da conservare o portare su un telefono nuovo.'),
    'backup_creating': ('Preparing the backup…', 'Preparo il backup…'),
    'backup_createFailed': ('The backup could not be created. Try again.', 'Non sono riuscito a creare il backup. Riprova.'),
    'backup_subject': ('Film Tracker backup', 'Backup di Film Tracker'),
    'backup_restore': ('Restore from a backup', 'Ripristina da un backup'),
    'backup_restoreBody': ('Bring back rolls and photos from a file made with “Back up everything”.',
                           'Riporta rullini e foto da un file fatto con «Fai un backup di tutto».'),
    'backup_restoreTitle': ('What to do with this backup?', 'Cosa faccio con questo backup?'),
    'backup_restoreSummary': ('Rolls: {rolls} · cameras: {cameras} · photos: {images}.',
                              'Rullini: {rolls} · macchine: {cameras} · foto: {images}.'),
    'backup_restoring': ('Restoring…', 'Ripristino in corso…'),
    'backup_modeReplace': ('Replace everything', 'Sostituisci tutto'),
    'backup_modeReplaceBody': ('What’s on this phone now is deleted, photos included, and replaced by the backup.',
                               'Quello che c’è ora su questo telefono si cancella, foto comprese, e al suo posto va il backup.'),
    'backup_modeMerge': ('Add to what I have', 'Aggiungi a quello che ho'),
    'backup_modeMergeBody': ('Rolls already on this phone are skipped; a roll whose number is taken gets the next free one.',
                             'I rullini già presenti vengono saltati; un rullino con un numero già usato prende il primo libero.'),
    'backup_restored': ('Backup restored', 'Backup ripristinato'),
    'backup_failed': ('That file isn’t a Film Tracker backup, or it’s damaged.',
                      'Quel file non è un backup di Film Tracker, o è rovinato.'),
}

TIPI = {
    'rolls': 'int', 'cameras': 'int', 'images': 'int',
}
